# Site settings
title: Creative blog
email: vadic_m@mail.ru
description: > # this means to ignore newlines until "baseurl:"
  Vadim Melnikov
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
encoding: UTF-8 # кодировка
# Build settings
markdown: kramdown
paginate: 2